version: '3.8'
services:
  database_pg:
    image: postgres:10
    volumes:
      - ./postgres/data:/var/lib/postgresql/data # <-- bind the database to local directory
    env_file:
      - database_env
    networks:
      - db_network

  djangoapp:
    container_name: djangoapp
    build: .
    volumes:
      - .:/djangoapp # <-- bind the application code
      - ./staticfiles:/staticfiles  # <-- bind the static files
      - ./media:/media  # <-- bind the media files
    networks:
      - db_network
      - web_network

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./staticfiles:/staticfiles  # <-- bind the static files again so Nginx can share volume
      - ./media:/media  # <-- bind the media files again so Nginx can share volume
    networks:
      - web_network
    depends_on: 
      - djangoapp

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
